// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XPueGBLl-Pxaz7GQkTIctrXt5LdhAlo',
    appId: '1:661020500976:web:1c298688b0070a1cab7335',
    messagingSenderId: '661020500976',
    projectId: 'clean-arch-b5b67',
    authDomain: 'clean-arch-b5b67.firebaseapp.com',
    storageBucket: 'clean-arch-b5b67.firebasestorage.app',
    measurementId: 'G-NLX11EY2M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByNPZwpR46NKUiRrE9Dc9I9csabjM7sbY',
    appId: '1:661020500976:android:6c55413693b0a0a8ab7335',
    messagingSenderId: '661020500976',
    projectId: 'clean-arch-b5b67',
    storageBucket: 'clean-arch-b5b67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHvhSyPImnJvEVtt_TNuidZ8ZNvTppm_I',
    appId: '1:661020500976:ios:dbca7cf400643bb4ab7335',
    messagingSenderId: '661020500976',
    projectId: 'clean-arch-b5b67',
    storageBucket: 'clean-arch-b5b67.firebasestorage.app',
    iosBundleId: 'com.example.cleanarch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHvhSyPImnJvEVtt_TNuidZ8ZNvTppm_I',
    appId: '1:661020500976:ios:dbca7cf400643bb4ab7335',
    messagingSenderId: '661020500976',
    projectId: 'clean-arch-b5b67',
    storageBucket: 'clean-arch-b5b67.firebasestorage.app',
    iosBundleId: 'com.example.cleanarch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9XPueGBLl-Pxaz7GQkTIctrXt5LdhAlo',
    appId: '1:661020500976:web:ff636af44855dba5ab7335',
    messagingSenderId: '661020500976',
    projectId: 'clean-arch-b5b67',
    authDomain: 'clean-arch-b5b67.firebaseapp.com',
    storageBucket: 'clean-arch-b5b67.firebasestorage.app',
    measurementId: 'G-D0Y8869VWC',
  );
}
